// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LastModified         int64    `protobuf:"varint,3,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	Version              int32    `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Group                string   `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	Properties           []byte   `protobuf:"bytes,6,opt,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Config) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Config) GetLastModified() int64 {
	if m != nil {
		return m.LastModified
	}
	return 0
}

func (m *Config) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Config) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Config) GetProperties() []byte {
	if m != nil {
		return m.Properties
	}
	return nil
}

type StoreConfigRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Group                string   `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	Properties           []byte   `protobuf:"bytes,6,opt,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreConfigRequest) Reset()         { *m = StoreConfigRequest{} }
func (m *StoreConfigRequest) String() string { return proto.CompactTextString(m) }
func (*StoreConfigRequest) ProtoMessage()    {}
func (*StoreConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}
func (m *StoreConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreConfigRequest.Unmarshal(m, b)
}
func (m *StoreConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreConfigRequest.Marshal(b, m, deterministic)
}
func (m *StoreConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreConfigRequest.Merge(m, src)
}
func (m *StoreConfigRequest) XXX_Size() int {
	return xxx_messageInfo_StoreConfigRequest.Size(m)
}
func (m *StoreConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreConfigRequest proto.InternalMessageInfo

func (m *StoreConfigRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StoreConfigRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StoreConfigRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *StoreConfigRequest) GetProperties() []byte {
	if m != nil {
		return m.Properties
	}
	return nil
}

type RetrieveConfigRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId              string   `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveConfigRequest) Reset()         { *m = RetrieveConfigRequest{} }
func (m *RetrieveConfigRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveConfigRequest) ProtoMessage()    {}
func (*RetrieveConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{2}
}
func (m *RetrieveConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveConfigRequest.Unmarshal(m, b)
}
func (m *RetrieveConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveConfigRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveConfigRequest.Merge(m, src)
}
func (m *RetrieveConfigRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveConfigRequest.Size(m)
}
func (m *RetrieveConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveConfigRequest proto.InternalMessageInfo

func (m *RetrieveConfigRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RetrieveConfigRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "grpc.Config")
	proto.RegisterType((*StoreConfigRequest)(nil), "grpc.StoreConfigRequest")
	proto.RegisterType((*RetrieveConfigRequest)(nil), "grpc.RetrieveConfigRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfigServiceClient interface {
	StoreConfig(ctx context.Context, in *StoreConfigRequest, opts ...grpc.CallOption) (*Config, error)
	RetrieveConfig(ctx context.Context, in *RetrieveConfigRequest, opts ...grpc.CallOption) (*Config, error)
}

type configServiceClient struct {
	cc *grpc.ClientConn
}

func NewConfigServiceClient(cc *grpc.ClientConn) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) StoreConfig(ctx context.Context, in *StoreConfigRequest, opts ...grpc.CallOption) (*Config, error) {
	out := new(Config)
	err := c.cc.Invoke(ctx, "/grpc.ConfigService/StoreConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) RetrieveConfig(ctx context.Context, in *RetrieveConfigRequest, opts ...grpc.CallOption) (*Config, error) {
	out := new(Config)
	err := c.cc.Invoke(ctx, "/grpc.ConfigService/RetrieveConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the Handler API for ConfigService service.
type ConfigServiceServer interface {
	StoreConfig(context.Context, *StoreConfigRequest) (*Config, error)
	RetrieveConfig(context.Context, *RetrieveConfigRequest) (*Config, error)
}

func RegisterConfigServiceServer(s *grpc.Server, srv ConfigServiceServer) {
	s.RegisterService(&_ConfigService_serviceDesc, srv)
}

func _ConfigService_StoreConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).StoreConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ConfigService/StoreConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).StoreConfig(ctx, req.(*StoreConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_RetrieveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).RetrieveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ConfigService/RetrieveConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).RetrieveConfig(ctx, req.(*RetrieveConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConfigService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreConfig",
			Handler:    _ConfigService_StoreConfig_Handler,
		},
		{
			MethodName: "RetrieveConfig",
			Handler:    _ConfigService_RetrieveConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config.proto",
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe5, 0x36, 0x49, 0xe1, 0x48, 0x3b, 0x9c, 0x40, 0x32, 0x20, 0xa1, 0xa8, 0x2c, 0x99,
	0x32, 0x80, 0x98, 0xd8, 0x60, 0x62, 0x60, 0x71, 0x1f, 0xa0, 0x2a, 0xf1, 0x35, 0x3a, 0x89, 0xc6,
	0xc6, 0x71, 0xf3, 0x02, 0x3c, 0x09, 0x6f, 0x8a, 0x6a, 0x07, 0xa9, 0x15, 0x48, 0x20, 0x36, 0xff,
	0xdf, 0xf9, 0xee, 0xff, 0xcf, 0x86, 0xbc, 0x36, 0xed, 0x9a, 0x9b, 0xca, 0x3a, 0xe3, 0x0d, 0x26,
	0x8d, 0xb3, 0xf5, 0xfc, 0x43, 0x40, 0xf6, 0x18, 0x30, 0xce, 0x60, 0xc4, 0x5a, 0x8a, 0x42, 0x94,
	0xc7, 0x6a, 0xc4, 0x1a, 0x11, 0x92, 0x76, 0xb5, 0x21, 0x39, 0x0a, 0x24, 0x9c, 0xf1, 0x1a, 0xa6,
	0xaf, 0xab, 0xce, 0x2f, 0x37, 0x46, 0xf3, 0x9a, 0x49, 0xcb, 0x71, 0x21, 0xca, 0xb1, 0xca, 0x77,
	0xf0, 0x79, 0x60, 0x28, 0x61, 0xd2, 0x93, 0xeb, 0xd8, 0xb4, 0x32, 0x29, 0x44, 0x99, 0xaa, 0x2f,
	0x89, 0xa7, 0x90, 0x36, 0xce, 0x6c, 0xad, 0x4c, 0xc3, 0xcc, 0x28, 0xf0, 0x0a, 0xc0, 0x3a, 0x63,
	0xc9, 0x79, 0xa6, 0x4e, 0x66, 0x85, 0x28, 0x73, 0xb5, 0x47, 0xe6, 0x2d, 0xe0, 0xc2, 0x1b, 0x47,
	0x31, 0xa7, 0xa2, 0xb7, 0x2d, 0x75, 0xfe, 0x4f, 0x71, 0xff, 0xe7, 0xf7, 0x00, 0x67, 0x8a, 0xbc,
	0x63, 0xea, 0x7f, 0xb1, 0x3c, 0x87, 0xa3, 0x30, 0x71, 0xc9, 0x7a, 0xb0, 0x9d, 0x04, 0xfd, 0xa4,
	0x6f, 0xde, 0x05, 0x4c, 0x63, 0xf3, 0x82, 0x5c, 0xcf, 0x35, 0xe1, 0x1d, 0x9c, 0xec, 0x6d, 0x81,
	0xb2, 0xda, 0xbd, 0x7f, 0xf5, 0x7d, 0xb1, 0x8b, 0x3c, 0x56, 0x86, 0x7b, 0xf7, 0x30, 0x3b, 0x0c,
	0x83, 0x97, 0xb1, 0xfe, 0x63, 0xc4, 0xc3, 0xe6, 0x97, 0x2c, 0x7c, 0xf5, 0xed, 0x67, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x74, 0x42, 0x34, 0xe7, 0xfa, 0x01, 0x00, 0x00,
}
